# 開発用コンテナ群

version: "3.7"
services:
  mykaggle:
    image: cfiken/mykaggle:python
    shm_size: '256gb'
    command: ["poetry", "run", "jupyter", "lab", "--port", "8888", "--config", "jupyter_notebook_config.py"]
    container_name: mykaggle
    restart: "no"
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: $SSH_AUTH_SOCK
        target: /ssh-agent
      - type: bind
        source: ~/.aws
        target: /home/ubuntu/.aws
      - type: bind
        source: ~/.kaggle
        target: /home/ubuntu/.kaggle
    environment:
      SSH_AUTH_SOCK: /ssh-agent
      MLFLOW_TRACKING_URI: $MLFLOW_TRACKING_URI
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      MY_SLACK_WEBHOOK_URL: $MY_SLACK_WEBHOOK_URL
    tty: true
    stdin_open: true
