[tool.poetry]
name = "mykaggle"
version = "0.1.0"
description = ""
authors = ["cfiken <cfiken@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8.6, <4.0.0"
jupyter = "*"
jupyterlab = "*"
numpy = "*"
matplotlib = "*"
pillow = "*"
pandas = "*"
seaborn = "*"
lightgbm = "*"
tensorflow = "2.2.1"
tensorflow-addons = "*"
tensorflow-datasets = "*"
transformers = "*"
torch = "1.4.0"
torchvision = "*"
fastprogress = "*"
kaggle = "*"
pyyaml = "*"
mlflow = "*"


[tool.poetry.dev-dependencies]
pytest = "*"
flake8 = "*"
mypy = "*"
autopep8 = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
