[tool.poetry]
name = "mykaggle"
version = "0.1.0"
description = ""
authors = ["cfiken <cfiken@gmail.com>"]

[tool.poetry.dependencies]
python = "=3.10.4"
jupyter = "*"
jupyterlab = "*"
numpy = "*"
matplotlib = "*"
pillow = "*"
pandas = "*"
seaborn = "*"
lightgbm = "*"
xgboost = "*"
catboost = "*"
# tensorflow = "2.2.1"
# tensorflow-addons = "*"
# tensorflow-datasets = "*"
transformers = "*"
fastprogress = "*"
kaggle = "*"
pyyaml = "*"
mlflow = "*"
python-dotenv = "^0.15.0"
boto3 = "^1.17.23"
types-PyYAML = "^5.4.6"
types-requests = "^2.25.6"
category-encoders = "^2.5.0"
#torch = {url = "https://download.pytorch.org/whl/cu113/torch-1.11.0%2Bcu113-cp38-cp38-linux_x86_64.whl"}
#torch = { version = "=1.11.0+cu113", source = "pytorch-cu113" }
#torchvision = { version = "=0.12.0+cu113", source = "pytorch-cu113" }
protobuf = "^3.20.0"
opencv-python = "^4.6.0.66"
albumentations = "^1.2.0"
pyarrow = "^8.0.0"
datasets = "^2.3.2"
sentencepiece = "^0.1.96"
fsspec = "^2022.5.0"
timm = "^0.5.4"

[tool.poetry.dev-dependencies]
pytest = "*"
flake8 = "*"
mypy = "*"
autopep8 = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

#[[tool.poetry.source]]
#name = "pytorch-cu113"
# url = "https://download.pytorch.org/whl/cu113/"
# secondary = true

