# Python CircleCI 2.0 configuration file
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8.6

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ checksum "poetry.lock" }}-{{ checksum ".circleci/config.yml" }}

      - run:
          name: install dependencies
          command: |
            poetry install 

      - save_cache:
          paths:
            - ./.venv
          key: dependencies-{{ checksum "poetry.lock" }}-{{ checksum ".circleci/config.yml" }}

      - run: 
          name: run tests
          command: |
            poetry run pytest

      - run:
          name: run flake8
          command: |
            poetry run flake8

      - run:
          name: run mypy
          command: |
            poetry run mypy ./ --ignore-missing
